plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ieumsae'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {

	// =========================
	// Spring Boot Starter
	// =========================

	// JPA / Hibernate
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	// DB 마이그레이션 (Flyway)
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-mysql'

	// Spring Security
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-data-redis'

	// Validation (@Valid, @NotNull 등)
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	// Web MVC / REST API
	implementation 'org.springframework.boot:spring-boot-starter-web'

	// Spring Batch
	implementation 'org.springframework.boot:spring-boot-starter-batch'

	// Distributed scheduler lock
	implementation 'net.javacrumbs.shedlock:shedlock-spring:6.9.2'
	implementation 'net.javacrumbs.shedlock:shedlock-provider-jdbc-template:6.9.2'

	// =========================
	// Authentication
	// =========================

	// JWT
	implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

	// =========================
	// AWS
	// =========================

	implementation platform('software.amazon.awssdk:bom:2.25.60')
	implementation 'software.amazon.awssdk:s3'


	// =========================
	// Database
	// =========================

	// MariaDB Driver
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'


	// =========================
	// QueryDSL
	// =========================

	// QueryDSL JPA
	implementation 'com.querydsl:querydsl-jpa:5.1.0:jakarta'

	// QClass 자동 생성
	annotationProcessor 'com.querydsl:querydsl-apt:5.1.0:jakarta'

	// Jakarta
	implementation 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.annotation:jakarta.annotation-api'
	annotationProcessor 'jakarta.persistence:jakarta.persistence-api'


	// =========================
	// Lombok
	// =========================

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'


	// =========================
	// Test
	// =========================

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'

	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'

	testRuntimeOnly 'com.h2database:h2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
	systemProperty 'spring.profiles.active', 'test'
}


// =========================
// QueryDSL Generated Source
// =========================

def querydslDir = layout.buildDirectory.dir("generated/querydsl").get().asFile

sourceSets {
	main {
		java {
			srcDirs += querydslDir
		}
	}
}

tasks.withType(JavaCompile).configureEach {
	options.generatedSourceOutputDirectory = querydslDir
}
