package com.ieumsae.assetieum.domain.notification.type;

public enum NotificationType {
	TICKET_STATUS_CHANGED,
	INSPECTION_STARTED,
	INSPECTION_ENDING,
	INSPECTION_REMINDER,
	INTANGIBLE_ASSET_EXPIRED,
	INTANGIBLE_ASSET_EXPIRING_TOMORROW,
	INTANGIBLE_ASSET_PAYMENT_DUE,
	RENTAL_RETURN_DUE_TOMORROW,
	RENTAL_RETURN_DUE_TODAY,
	RENTAL_RETURN_OVERDUE
}
