CREATE TABLE BATCH_JOB_INSTANCE
(
    JOB_INSTANCE_ID BIGINT       NOT NULL PRIMARY KEY,
    VERSION         BIGINT       NULL,
    JOB_NAME        VARCHAR(100) NOT NULL,
    JOB_KEY         VARCHAR(32)  NOT NULL,
    CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
) ENGINE = InnoDB;

CREATE TABLE BATCH_JOB_EXECUTION
(
    JOB_EXECUTION_ID BIGINT        NOT NULL PRIMARY KEY,
    VERSION          BIGINT        NULL,
    JOB_INSTANCE_ID  BIGINT        NOT NULL,
    CREATE_TIME      DATETIME(6)   NOT NULL,
    START_TIME       DATETIME(6)   NULL,
    END_TIME         DATETIME(6)   NULL,
    STATUS           VARCHAR(10)   NULL,
    EXIT_CODE        VARCHAR(2500) NULL,
    EXIT_MESSAGE     VARCHAR(2500) NULL,
    LAST_UPDATED     DATETIME(6)   NULL,
    CONSTRAINT JOB_INST_EXEC_FK
        FOREIGN KEY (JOB_INSTANCE_ID) REFERENCES BATCH_JOB_INSTANCE (JOB_INSTANCE_ID)
) ENGINE = InnoDB;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS
(
    JOB_EXECUTION_ID BIGINT        NOT NULL,
    PARAMETER_NAME   VARCHAR(100)  NOT NULL,
    PARAMETER_TYPE   VARCHAR(100)  NOT NULL,
    PARAMETER_VALUE  VARCHAR(2500) NULL,
    IDENTIFYING      CHAR(1)       NOT NULL,
    CONSTRAINT JOB_EXEC_PARAMS_FK
        FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE = InnoDB;

CREATE TABLE BATCH_STEP_EXECUTION
(
    STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
    VERSION            BIGINT        NOT NULL,
    STEP_NAME          VARCHAR(100)  NOT NULL,
    JOB_EXECUTION_ID   BIGINT        NOT NULL,
    CREATE_TIME        DATETIME(6)   NOT NULL,
    START_TIME         DATETIME(6)   NULL,
    END_TIME           DATETIME(6)   NULL,
    STATUS             VARCHAR(10)   NULL,
    COMMIT_COUNT       BIGINT        NULL,
    READ_COUNT         BIGINT        NULL,
    FILTER_COUNT       BIGINT        NULL,
    WRITE_COUNT        BIGINT        NULL,
    READ_SKIP_COUNT    BIGINT        NULL,
    WRITE_SKIP_COUNT   BIGINT        NULL,
    PROCESS_SKIP_COUNT BIGINT        NULL,
    ROLLBACK_COUNT     BIGINT        NULL,
    EXIT_CODE          VARCHAR(2500) NULL,
    EXIT_MESSAGE       VARCHAR(2500) NULL,
    LAST_UPDATED       DATETIME(6)   NULL,
    CONSTRAINT JOB_EXEC_STEP_FK
        FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE = InnoDB;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT
(
    STEP_EXECUTION_ID  BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT          NULL,
    CONSTRAINT STEP_EXEC_CTX_FK
        FOREIGN KEY (STEP_EXECUTION_ID) REFERENCES BATCH_STEP_EXECUTION (STEP_EXECUTION_ID)
) ENGINE = InnoDB;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT
(
    JOB_EXECUTION_ID   BIGINT        NOT NULL PRIMARY KEY,
    SHORT_CONTEXT      VARCHAR(2500) NOT NULL,
    SERIALIZED_CONTEXT TEXT          NULL,
    CONSTRAINT JOB_EXEC_CTX_FK
        FOREIGN KEY (JOB_EXECUTION_ID) REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID)
) ENGINE = InnoDB;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775806
    INCREMENT BY 1
    NOCACHE
    NOCYCLE
    ENGINE = InnoDB;

CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775806
    INCREMENT BY 1
    NOCACHE
    NOCYCLE
    ENGINE = InnoDB;

CREATE SEQUENCE BATCH_JOB_SEQ
    START WITH 1
    MINVALUE 1
    MAXVALUE 9223372036854775806
    INCREMENT BY 1
    NOCACHE
    NOCYCLE
    ENGINE = InnoDB;
